[debug] [2017-11-17T22:43:31.560Z] ----------------------------------------------------------------------
[debug] [2017-11-17T22:43:31.562Z] Command:       /usr/local/bin/node /Users/michaeldouglas/fullstack_github/capstoneCrossover/capstoneCrossover/node_modules/.bin/firebase serve --only functions,hosting
[debug] [2017-11-17T22:43:31.562Z] CLI Version:   3.14.0
[debug] [2017-11-17T22:43:31.562Z] Platform:      darwin
[debug] [2017-11-17T22:43:31.562Z] Node Version:  v8.5.0
[debug] [2017-11-17T22:43:31.563Z] Time:          Fri Nov 17 2017 17:43:31 GMT-0500 (EST)
[debug] [2017-11-17T22:43:31.563Z] ----------------------------------------------------------------------
[debug] 
[debug] [2017-11-17T22:43:31.577Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2017-11-17T22:43:31.578Z] > authorizing via signed-in user
[debug] [2017-11-17T22:43:31.580Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/crossover-cf663  
 Fri Nov 17 2017 17:43:31 GMT-0500 (EST)
[debug] [2017-11-17T22:43:31.949Z] <<< HTTP RESPONSE 200
[debug] [2017-11-17T22:43:31.950Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/crossover-cf663/tokens  
 Fri Nov 17 2017 17:43:31 GMT-0500 (EST)
[debug] [2017-11-17T22:43:32.409Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/Users/michaeldouglas/fullstack_github/capstoneCrossover/capstoneCrossover'...
[info] 
[info] i  functions: Preparing to emulate functions.
[debug] [2017-11-17T22:43:32.917Z] >>> HTTP REQUEST GET https://appengine.googleapis.com/v1/apps/crossover-cf663  
 Fri Nov 17 2017 17:43:32 GMT-0500 (EST)
[debug] [2017-11-17T22:43:32.917Z] >>> HTTP REQUEST GET https://apikeys.googleapis.com/v1/projects/crossover-cf663/apiKeys  
 Fri Nov 17 2017 17:43:32 GMT-0500 (EST)
[debug] [2017-11-17T22:43:32.918Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/crossover-cf663  
 Fri Nov 17 2017 17:43:32 GMT-0500 (EST)
[debug] [2017-11-17T22:43:33.203Z] <<< HTTP RESPONSE 200
[debug] [2017-11-17T22:43:33.220Z] <<< HTTP RESPONSE 200
[debug] [2017-11-17T22:43:33.224Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/311688361311/clients/_:getWebAppConfig  
 Fri Nov 17 2017 17:43:33 GMT-0500 (EST)
[debug] [2017-11-17T22:43:33.309Z] <<< HTTP RESPONSE 200
[debug] [2017-11-17T22:43:33.777Z] <<< HTTP RESPONSE 200
[info] i  hosting: Serving hosting files from: public
[info] ✔  hosting: Local server: http://localhost:5000

[info] ✔  functions: helloWorld: http://localhost:5001/crossover-cf663/us-central1/helloWorld
[info] Shutting down...
[debug] [2017-11-17T22:46:35.941Z] Error: write EPIPE
    at _errnoException (util.js:1026:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:858:14)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2017-11-17T22:46:35.946Z] Error: write EPIPE
    at _errnoException (util.js:1026:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:858:14)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2017-11-17T22:46:54.135Z] ----------------------------------------------------------------------
[debug] [2017-11-17T22:46:54.139Z] Command:       /usr/local/bin/node /Users/michaeldouglas/fullstack_github/capstoneCrossover/capstoneCrossover/node_modules/.bin/firebase serve --only functions,hosting
[debug] [2017-11-17T22:46:54.140Z] CLI Version:   3.14.0
[debug] [2017-11-17T22:46:54.140Z] Platform:      darwin
[debug] [2017-11-17T22:46:54.140Z] Node Version:  v8.5.0
[debug] [2017-11-17T22:46:54.141Z] Time:          Fri Nov 17 2017 17:46:54 GMT-0500 (EST)
[debug] [2017-11-17T22:46:54.141Z] ----------------------------------------------------------------------
[debug] 
[debug] [2017-11-17T22:46:54.158Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2017-11-17T22:46:54.159Z] > authorizing via signed-in user
[debug] [2017-11-17T22:46:54.161Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/crossover-cf663  
 Fri Nov 17 2017 17:46:54 GMT-0500 (EST)
[debug] [2017-11-17T22:46:54.590Z] <<< HTTP RESPONSE 200
[debug] [2017-11-17T22:46:54.591Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/crossover-cf663/tokens  
 Fri Nov 17 2017 17:46:54 GMT-0500 (EST)
[debug] [2017-11-17T22:46:54.966Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/Users/michaeldouglas/fullstack_github/capstoneCrossover/capstoneCrossover'...
[info] 
[info] i  functions: Preparing to emulate functions.
[debug] [2017-11-17T22:46:55.476Z] >>> HTTP REQUEST GET https://appengine.googleapis.com/v1/apps/crossover-cf663  
 Fri Nov 17 2017 17:46:55 GMT-0500 (EST)
[debug] [2017-11-17T22:46:55.476Z] >>> HTTP REQUEST GET https://apikeys.googleapis.com/v1/projects/crossover-cf663/apiKeys  
 Fri Nov 17 2017 17:46:55 GMT-0500 (EST)
[debug] [2017-11-17T22:46:55.477Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/crossover-cf663  
 Fri Nov 17 2017 17:46:55 GMT-0500 (EST)
[debug] [2017-11-17T22:46:55.764Z] <<< HTTP RESPONSE 200
[debug] [2017-11-17T22:46:55.768Z] <<< HTTP RESPONSE 200
[debug] [2017-11-17T22:46:55.769Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/311688361311/clients/_:getWebAppConfig  
 Fri Nov 17 2017 17:46:55 GMT-0500 (EST)
[debug] [2017-11-17T22:46:55.821Z] <<< HTTP RESPONSE 200
[debug] [2017-11-17T22:46:56.056Z] <<< HTTP RESPONSE 200
[info] i  hosting: Serving hosting files from: public
[info] ✔  hosting: Local server: http://localhost:5000

[info] ✔  functions: helloWorld: http://localhost:5001/crossover-cf663/us-central1/helloWorld
[info] Shutting down...
[debug] [2017-11-17T23:49:28.907Z] Error: write EPIPE
    at _errnoException (util.js:1026:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:858:14)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2017-11-17T23:49:28.914Z] Error: write EPIPE
    at _errnoException (util.js:1026:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:858:14)
[error] 
[error] Error: An unexpected error has occurred.
